# This is a basic workflow to help you get started with Actions

name: russian roulette of assignees

on:
  issues:
    types: [opened]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: select random assignee
      shell: bash
      run: |
        assignees=($(jq --raw-output '.issue.assignees[].login' "${GITHUB_EVENT_PATH}"))
        echo "assignee: ${assignee[@]}"
