# This is a basic workflow to help you get started with Actions

name: russian roulette of assignees

on:
  issues:
    types: [opened]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: select random assignee
      shell: bash
      run: |
        action=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
        number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        assignee=$(jq --raw-output .assignee.login "$GITHUB_EVENT_PATH")
        echo "action: ${action}"
        echo "number: ${number}"
        echo "assignee: ${assignee}"
